name: String.levenshtein
author: thinkphp
current: v1.0  
category: utilities 
tags: [algoritm, distance,levenshtein,string,similary]
docs: http://github.com/thinkphp/String.levenshtein/blob/master/Docs/String.levenshtein.md 
demo: http://thinkphp.ro/apps/js-hacks/String.levenshtein/String.levenshtein.html
